@startuml

class Order {
  date
  prepaid
  number
  price
}

class Customer {
  name
  address
  ratings
}

class OrderLine {
  Product
  Price
  Quantity
}

class Corporate {
  name
  rating
  limit
}

class Personal {
  id
  contact
}

Order "1" --> "n" Customer
Order "1" --> "n" OrderLine
Customer <|-- Corporate
Customer <|-- Personal

@enduml