Here is the PlantUML notation for the given UML class diagram:

```plantuml
@startuml
class Person {
    name: String
}

class User {
    userName: String
    password: String
}

Person <|-- User
@enduml
```