@startuml
class Interaction {
  -processId : String
}

class Lifeline {
  -terminated : boolean
}

class Object {
  -name : String
  -class : String
}

class Message {
  -operation : String
  -sequenceNumber : String
}

Interaction "1" *-- "0..*" Lifeline : instances
Lifeline "1" -- "0..1" Object : object
Lifeline "1" -- "*" Message : from
Lifeline "1" -- "*" Message : to
@enduml