@startuml
' TODO: Assuming "date" and "status" are attributes of Order; no types specified.
' TODO: Assuming "amount" is attribute of Payment; no type specified.
' TODO: Assuming "cash" is attribute of Cash; no type specified.
' TODO: Assuming "name", "id" are attributes of Check; no types specified.
' TODO: Assuming "number", "type", "date" are attributes of Credit; no types specified.
' TODO: Association between Order and Payment is aggregation (diamond on Payment side) with multiplicity 1 Order to * Payments.

class Order {
  date
  status
}

class Payment {
  amount
}

class Cash {
  cash
}

class Check {
  name
  id
}

class Credit {
  number
  type
  date
}

Order "1" o-- "*" Payment

Payment <|-- Cash
Payment <|-- Check
Payment <|-- Credit

@enduml