@startuml
' TODO: No attributes or operations shown; assuming empty classes.
' TODO: All associations are undirected; multiplicities and roles inferred from labels and positions.

class Tenant {
}

class House {
}

class Landlord {
}

class MaintenanceAgency {
}

class RealEstateAgency {
}

Tenant "0..1" -- "*" House : lease
House "*" -- "*" Landlord
House "*" -- "0..1" MaintenanceAgency : maintain
House "*" -- "*" RealEstateAgency

@enduml