Here's the PlantUML representation of the UML class diagram:

```plaintext
@startuml
class Tenant
class House
class Landlord
class RealEstateAgency
class MaintenanceAgency

Tenant "0..1" -- "1" House : lease
Landlord "1" -- "1" House : *
RealEstateAgency "1" -- "*" House : *
MaintenanceAgency "0..1" -- "1" House : maintains
@enduml
```