@startuml
class StockManager {}

class Part {
  name
}

class BasicPart {
  unitPrice
}

class CompoundPart {
  cost
}

Part <|-- BasicPart
Part <|-- CompoundPart

StockManager "0..1" -- "*" Part

@enduml