```plantuml
@startuml

class Task {
    name: string
}

class Worker {
    name: string
}

class PeriodicTask {
    periodicity: string
}

Worker "0..1" --o "1" PeriodicTask
PeriodicTask --|> Task

@enduml
```