```plantuml
@startuml

class Student {
    name
    address
    phone
    id
    mark
}

class Enrollment {
    marks
}

class Seminar {
    name
    id
    fees
}

class Professor {
    name
    address
    phone
    email
    salary
}

Student "1" -left-> "1..*" Enrollment : enrolled
Student "0..*" --> "1..*" Seminar : on waiting list
Enrollment "1..*" --> "1" Seminar : in
Professor "0..*" --> Seminar : instructs

@enduml
```