@startuml

class Order {
    dateReceived
    isPrepaid
    number
    price
}

class OrderLine {
    quantity
    price
}

class Product {
}

class Customer {
    name
    address
}

class CorporateCustomer {
    contact
    creditRate
    creditLimit
}

class PersonalCustomer {
    creditCard
}

class Employee {
}

Order "1" -- "*" OrderLine
Order "1" --> "*" Customer
OrderLine "1" --> "*" Product
Customer <|-- CorporateCustomer
Customer <|-- PersonalCustomer
CorporateCustomer "0..1" --> "*" Employee

@enduml