```plantuml
@startuml

class Bank {
}

class Customer {
}

class Account {
}

class AccountDetail {
}

class Staff {
}

class CustomerRecord {
}

Bank "1" --> "*" Customer
Customer "*" --> "*" Account
Account "1" --> "1" AccountDetail
Staff "1" --> "*" Bank
CustomerRecord "*" --> "1" Customer

@enduml
```