@startuml

class Family {
  familyName : String
}

class FamilyMember {
  memberName : String
}

Family "0..1" -- "*" FamilyMember : father
Family "0..1" -- "*" FamilyMember : mother
Family "0..1" -- "*" FamilyMember : sons
Family "0..1" -- "*" FamilyMember : daughters

@enduml