@startuml
' TODO: Assumed all associations are bidirectional unless explicitly directed.
' TODO: Multiplicity 'n' or '*' are treated as '*' per requirement.
' TODO: No visibility specified, assumed public for all attributes.

class Journey {
  jId: String
}

class Route {
  rId: String
}

class Place {
  pId: String
  name: String
  x: double
  y: double
}

class TransportMode {
  name: String
  emission: double
}

Journey "1" -- "*" Route : possibleRoutes
Route "1" -- "*" Place : locations
Place "1" -- "*" TransportMode : from
Place "1" -- "*" TransportMode : to

@enduml