@startuml

class OCR {
}

class Region {
    x1 : int
    y1 : int
    x2 : int
    y2 : int
}

class Content {
    text : String
}

OCR "1" -- "0..*" Region : regions
Region "1" -- "0..*" Content : content

@enduml