@startuml

class Bank {
    name: String
}

class BankBranch {
    sortCode: int
    address: String
}

class Customer {
    name: String
    cId: int
}

class Account {
    number: int
    balance: double
    overdrawn: boolean
}

Bank "1" -- "0..*" BankBranch : branches
Bank "1" -- "0..*" Customer : customers
Customer "1..*" -- "0..*" Account : owners
BankBranch "1" -- "0..*" Account : atBranch
Customer "0..*" -- "0..*" Account : accounts

@enduml