@startuml
class Bank {
  name : String
}

class BankBranch {
  sortCode : int
  address : String
}

class Customer {
  name : String
  cId : int
}

class Account {
  number : int
  balance : double
  overdrawn : boolean
}

Bank "1" *-- "*" BankBranch : branches
Bank "1" *-- "*" Customer : customers
BankBranch "1" *-- "*" Account : hosted
Customer "1..*" *-- "*" Account : owners / accounts

@enduml