@startuml
' TODO: Assuming "Program" contains multiple "Procedure" instances (composition) based on * and role "procedures"
' TODO: Assuming "Procedure" contains multiple "Statement" instances (composition) based on * and role "statement"

class Program {
  language: String
}

class Procedure {
  sequential: boolean
}

class Statement {
}

Program "1" *-- "*" Procedure : procedures
Procedure "1" *-- "*" Statement : statement

@enduml