@startuml

class SecuritySystem {
    location : string
}

class Monitor {
    location : int
    mode : int
}

class Alarm {
    on : boolean
}

class Controller {
    active : boolean
}

SecuritySystem "1" -- "1..*" Monitor : monitors
SecuritySystem "1" -- "1..*" Alarm : alarms
SecuritySystem "1" -- "1" Controller

@enduml