@startuml
left to right direction

class Language {
  name: String
  numberOfSpeakers: int
}

class UKEnglish
class USEnglish
class French {
  dialect: String
}

UKEnglish --|> Language
USEnglish --|> Language
French --|> Language
@enduml