@startuml
' Diagram shows Student—Degree Programme as one-to-many relationship
' Diagram shows Degree Programme—Module and Student—Module as many-to-many relationships
left to right direction

class Student

class "Degree Programme" {
  title: String
}

class Module {
  name: String
  weight: int
}

Student "*" -- "1" "Degree Programme" : students/programme
Student "*" -- "*" Module : attending
"Degree Programme" "*" -- "*" Module : modules/inProgramme

@enduml