@startuml

class Customer {
    - customerId : String
}

class Order {
    - orderNo : int
    - total : double
}

class OrderItem {
    - productCode : int
    - product : String
    - price : int
    - quantity : int
}

Customer "1" -- "*" Order : orders
Order "1" -- "*" OrderItem : items

@enduml