```plantuml
@startuml

class WebUser {
  - id: string
  - password: string
  - state: UserState
}

class Customer {
  - id: string
  - address: string
  - phone: Phone
  - email: string
}

class ShoppingCart {
  - date: string
}

class Account {
  - id: string
  - address
  - isClosed: boolean
  - openDate
  - closedDate
}

class Payment {
  - id: string
  - paidDate
  - total
  - details
}

class LineItem {
  - quantity
  - price
}

class Order {
  - number
  - date
  - shippedDate
  - address
  - status
  - total
}

class Product {
  - id
  - name
  - supplier
}

// Associations
WebUser "0..1" --> "1" ShoppingCart
WebUser "0..1" --> "1" Account
Customer "1" --> "0..1" Account
Account "0..1" --> "1" Order
Order "1" --> "0..*" LineItem
Order "1" --> "*" Payment
LineItem "1" --> "1" Product

@enduml
```