@startuml

class Bank {
    code
    address
}

class ATM {
    location
    manager
}

class Customer {
    name
    address
    dob
    cardNumber
    pin
}

class Account {
    number
    balance
}

class Transactions {
    id
    date
    type
    amount
    balance
}

class CurrentAccount {
    number
    balance
}

class SavingsAccount {
    accountNumber
    balance
}

Bank "1" -- "*" ATM
Bank "1" -- "*" Account
Customer "1" -- "*" Account
Account "1" -- "*" Transactions
Account <|-- CurrentAccount
Account <|-- SavingsAccount

@enduml