@startuml

class Publication {
    title: string
}

class Paperback {
    id: int
}

class Hardcover {
    id: int
}

class Compilation {
    id: int
    pages: int
}

class Sweeping {
    id: int
    pages: int
}

Publication "1" -- "n" Paperback
Publication "1" -- "n" Hardcover
Paperback <|-- Compilation
Paperback <|-- Sweeping
Hardcover <|-- Compilation
Hardcover <|-- Sweeping

@enduml