@startuml

class Person {
    name
    number
    email
}

class Address {
    street
    city
    state
    postcode
}

class Student {
    number
    mark
}

Person "0..1" -- "1" Address
Student --|> Person

@enduml