```plantuml
@startuml

class Journey {
    +jId : String
}

class Route {
    +rId : String
}

class Place {
    +pId : String
    +name : String
    +x : double
    +y : double
}

class TransportMode {
    +name : String
    +emissions : double
}

Journey "1" -- "0..*" Route : possibleRoutes
Route "0..*" -- "1" Place : from
Route "0..*" -- "1" Place : to
Route "0..*" -- "0..*" TransportMode

@enduml
```