@startuml

class OCR {
}

class Regim {
    x1: int
    y1: int
    x2: int
    y2: int
}

class Content {
    text: String
}

OCR "1" -- "0..*" Regim : regions / regions
Regim "1" -- "0..*" Content : content

@enduml