@startuml

class Bank {
    - name: String
}

class Customer {
    - name: String
    - cId: int
}

class Account {
    - number: int
    - balance: double
    - overdrawn: boolean
}

class BankBranch {
    - sortCode: int
    - address: String
}

Bank "1" -- "*" BankBranch : branches
Bank "*" -- "*" Customer : customers
Customer "1..*" -- "*" Account : owners
Account "*" -- "1" BankBranch : atBranch

@enduml