@startuml
' Assumed class name: "Bank Branch"
' Attribute "sortCode" assumed as "sortCode: int"
left to right direction

class Bank {
  name: String
}

class "Bank Branch" {
  sortCode: int
  address: String
}

class Customer {
  name: String
  cId: int
}

class Account {
  number: int
  balance: double
  overdrawn: boolean
}

Bank "1" -- "*" "Bank Branch" : branches
Bank "*" -- "*" Customer : customers
Customer "1..*" -- "*" Account : owners/accounts
"Bank Branch" "1" -- "*" Account : atBranch/hosted

@enduml