@startuml

class SecuritySystem {
    -location: String
}

class Monitor {
    -location: int
    -mode: int
}

class Alarm {
    -on: Boolean
}

class Controller {
    -active: Boolean
}

SecuritySystem "1" --> "*" Monitor : monitors
SecuritySystem "1" --> "*" Alarm : alarms
SecuritySystem "1" --> "1" Controller 

@enduml